polynum_blackboard/urls.py
from django.conf.urls import patterns, url


urlpatterns = patterns('polynum_blackboard.wizard',
    url(r'^request/(?P<pk>\d+)/edit/(?P<step>.+)/$', 'request_wizard_step', name='request_wizard_step'),
    url(r'^request/(?P<pk>\d+)/edit/$', 'request_wizard_step', name='request_wizard'),
)

urlpatterns += patterns('polynum_blackboard.views',
    url(r'^request/(?P<pk>\d+)/course-list/$', 'courses_list', name='courses_list'),
    url(r'^bb/create_course/', 'create_course', name='create_course'),
)

polynum_blackboard/forms.py
# -*- coding: utf-8 -*-

from django import forms
from django.utils.translation import ugettext_lazy as _

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Div, HTML, Field, Fieldset

from polynum.base.models import Entity
from polynum.request import widgets , forms as request_forms

import django_ws
import constant
import models
from . import app_settings

DEFAULT_CATEGORY = ''

def categories():
    '''Retrieve categories from MyCourse. Beware identifiers are the name of
       the categories not their id.
    '''
    yield ('', '---')
    ok, response = django_ws.get_bb_conn().get_categories()
    if ok:
        for category in response.categories:
            yield (category.name, category.name)


class func2iter(object):
    '''Adaptor to transform a generator returning function into an iterator.
       Each iteration() will come from a new generator.
    '''
    def __init__(self, func):
        self.func = func

    def __iter__(self):
        return self.func()


class CreateCourseForm(forms.Form):
    helper = FormHelper()
    helper.form_tag = False
    helper.layout = Layout(
            Div(
                HTML('<div id="id_course_label">&nbsp;</div>'),
                css_class='row-fluid'),
            'entity',
            Div(
                Div(Field('category', css_class="span12"), 
                    css_class="span8"),
                Div('td_group', css_class="span4"),
                css_class="row-fluid"),
            Div(
                Div('subscription_policy', css_class="span6"),
                Div('open_to_visitors', css_class="span6"),
                css_class="row-fluid"),
            Div(Field('password'), css_class="hide"))

    SUBSCRIPTION_POLICIES = (
            ('auto', u'oui'),
            ('password', u'avec mot de passe'),
            ('no', u'non'))
    entity = forms.ModelChoiceField(Entity.objects.all(),
            label=u'Unité d\'enseignement')
    category = forms.ChoiceField(label=u'Catégorie',
            choices=func2iter(categories))
    td_group = forms.CharField(label=u'Groupe de TD', max_length=16,
            required=False)
    open_to_visitors = forms.BooleanField(label=u'Ouvert aux visiteurs',
            required=False)
    subscription_policy = forms.ChoiceField(label=u'Auto-inscription', choices=SUBSCRIPTION_POLICIES,
            help_text=u'Si vous choisissez "Non", notez que vous devrez gérer'
            u' vous-même les inscriptions, avec votre secrétariat.')
    password = forms.CharField(label=u'Mot de passe', max_length=32, required=False)

    def __init__(self, request=None, *args, **kwargs):
        self.request = request
        super(CreateCourseForm, self).__init__(*args, **kwargs)
        self.fields['entity'].widget = widgets.MillerColumns(
                attrs={'data-entity-type': app_settings.UE_DESIGNATION})

    def clean(self):
        '''Check that category, subscription_policy and entity are correctly
           chosen. Generate a course_id.
        '''
        cleaned_data = self.cleaned_data
        if not cleaned_data.get('category'):
            cleaned_data['category'] = DEFAULT_CATEGORY
        if cleaned_data['subscription_policy'] == 'password' and not cleaned_data['password']:
            raise forms.ValidationError(u'vous devez fournir un mot de passe')
        if cleaned_data['entity'].entity_type.name != app_settings.UE_DESIGNATION:
            raise forms.ValidationError(u'vous devez sélectionner une UE')
        return cleaned_data

class MyCourseForm(request_forms.CopyrigtsForm):
    visible_to_students = forms.BooleanField(
            label=u'Document visible aux étudiants',
            initial=True)
    ue = forms.ModelChoiceField(Entity.objects.all(),
            label=u'Sinon sélectionnez l\'unité d\'enseignement dans \
laquelle vous souhaitez diffuser votre document')
    course_code = forms.CharField(max_length=128, widget=forms.HiddenInput)
    course_name = forms.CharField(max_length=128, widget=forms.HiddenInput)

    class Meta(request_forms.CopyrigtsForm.Meta):
        fields = ('copyright', 'licence')
        required = ('copyright', 'licence')

    def __init__(self, *args, **kwargs):
        instance = kwargs.get('instance', None)
        self.push = push = None
        if instance:
            try:
                self.push = push = models.BlackBoardPush.objects.get(request=instance)
            except models.BlackBoardPush.DoesNotExist:
                pass
        initial = kwargs.setdefault('initial', {})
        initial['ue'] = instance.entity.pk if instance and instance.entity else None
        if push:
            initial['course_name'] = push.course_name
        super(MyCourseForm, self).__init__(*args, **kwargs)
        self.fields['ue'].widget = widgets.MillerColumns(attrs={
            'data-entity-type': app_settings.UE_DESIGNATION
        })
        licence_pks_with_mycourse_tag = []
        for licence in self.fields['licence'].queryset:
            if constant.MYCOURSE_TAG in licence.diffusion_tags:
                licence_pks_with_mycourse_tag.append(licence.pk)
        self.helper.layout = Layout(
            Field('copyright', css_class="span12"),
            Field('licence', css_class="span12"),
            HTML('''
{% if form.course_name.errors %}
<div class="alert-error">
  {{ form.course_name.errors }}
</div>
{% endif %}'''),
            HTML('<script>var licence_pks_with_mycourse_tag = [%s];</script>' %
                    ', '.join(map(str, licence_pks_with_mycourse_tag))),
            Fieldset(u'Diffusion sur la plate-forme MyCourse',
                Div(
                    'visible_to_students',
                    HTML('{% include \'_select_my_course.html\' %}'),
                    HTML('{% include \'_select_sponsor_course.html\' %}'),
                    'ue',
                    'course_name',
                    'course_code',
                    HTML('{% include \'_select_ue_course.html\' %}')),
                    css_id='mycourse-block', css_class='hide'))

    def clean_course_name(self):
        if self.cleaned_data['licence'] and \
            constant.MYCOURSE_TAG in self.cleaned_data['licence'].diffusion_tags and \
            not self.cleaned_data.get('course_name'):
                raise forms.ValidationError(_(u'Vous devez choisir un cours'))
        return self.cleaned_data.get('course_name')

    def save(self, commit=True):
        instance = super(MyCourseForm, self).save(commit=commit)
        if self.cleaned_data['licence'] and \
            constant.MYCOURSE_TAG in self.cleaned_data['licence'].diffusion_tags:
            push, created = models.BlackBoardPush.objects.get_or_create(request=instance)
            push.course_code = self.cleaned_data['course_code']
            push.course_name = self.cleaned_data['course_name']
            push.visible_to_students = self.cleaned_data['visible_to_students']
            push.save()
        else:
            models.BlackBoardPush.objects.filter(request=instance).delete()
        return instance

    def pprint_data(self, data):
        ret = super(MyCourseForm, self).pprint_data(data)
        if self.push and self.push.course_name:
            ret.append((u'Déposer dans le cours', self.push.course_name, False))
            if app_settings.RESUME_MESSAGE:
                ret.append(('', app_settings.RESUME_MESSAGE, False))
        return ret

polynum_blackboard/templates/_courses_selector.html
  <select {% if not response.courses or error %}disabled{% endif %} class="courses-selector span8">
    {% if error %}
    <option value="">{{ error }}</option>
    {% elif not response.courses %}
    <option value="">Aucun cours disponible</option>
    {% else %}
    <option value="">---</option>
    {% for course in response.courses %}
    <option class="{% if not course.available %}unavailable{% endif %}" value="{{ course.id }}">{{ course.name }}{% if not course.available %} (indisponible){% endif %}</option>
    {% endfor %}
    {% endif %}
  </select>

polynum_blackboard/templates/_create_course.html
{% load url from future %}
{% load crispy_forms_tags %}
  <div id="create-course" class="modal hide fade large">
    <form action="{% url 'create_course' %}" method="POST">
      <input type="hidden" name="request-id" value="{{ object.id }}"/>
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3>Création d'un nouveau cours</h3>
      </div>
      <div class="modal-body">
        {% crispy create_course_form %}
      </div>
      <div class="modal-footer">
        <button type="button" data-dismiss="modal" class="btn">Fermer</button>
        <button class="btn btn-primary">Créer</button>
      </div>
    </form>
  </div>

polynum_blackboard/templates/_select_course.html
{% include "_select_my_course.html" %}

{% include "_select_sponsor_course.html" %}

{% include "_select_ue_course.html" %}

polynum_blackboard/templates/_select_my_course.html
{% load url from future %}
<style>
  .type-ue .controls button {
    height: auto;
  }
  .type-ue .controls.input-append {
    display: block;
  }
</style>
<div class="control-group type-owner">
  <label for="course-type-owner" class="control-label">Déposer le document dans un cours que je gère</label>
  <div class="controls">
    {% include '_courses_selector.html' with response=courses.user_courses error=courses.user_courses_error only %}
  </div>
</div>

polynum_blackboard/templates/_select_sponsor_course.html
{% load url from future %}
  <div class="control-group type-sponsor">
    <label for="course-type-sponsor" class="control-label">Ou bien déposer le document dans un cours que gère le commanditaire,</label>
    <div class="controls">
      {% include '_courses_selector.html' with response=courses.sponsor_courses error=courses.sponsor_courses_error only %}
    </div>
  </div>

polynum_blackboard/templates/_select_ue_course.html
{% load url from future %}
<div id="ue-course-container">
<div id="ue-course" class="control-group type-ue">
  <label for="course-type-ue" class="control-label">Et déposer le document dans un cours de cette unité d'enseignement</label>
  <div class="controls input-append">
    {% if not courses.ue %}
      <select class="courses-selector span8" disabled>
        <option value="">Vous n'avez pas sélectionné d'unité d'enseignement</option>
      </select>
      <button disabled data-target="#create-course" type="button" class="add-on btn" data-toggle="modal">Créer un nouveau cours</button>
    {% else %}
      {% include '_courses_selector.html' with response=courses.ue_courses error=courses.ue_courses_error only %}
      <button {% if courses.ue_courses_error %}disabled{% endif %} data-target="#create-course" type="button" class="add-on btn" data-toggle="modal">Créer un nouveau cours</button>
    {% endif %}
  </div>
</div>
</div>

polynum_blackboard/templates/document_copyrights.new_request.html
{% extends "base_document_copyrights.new_request.html" %}
{% load url from future %}
{% load sekizai_tags %}
{% load crispy_forms_tags %}
{% load editor %}

{% block extra_scripts %}
{{ block.super }}
{{ create_course_form.media.css }}
<style>
#create-course .miller-columns {
  height: 10em;
}
#create-course label {
  font-weight: bold;
}
.modal.large {
  margin: -300px 0px 0px -380px;
  width: 760px;
}
.modal.large .modal-body {
  max-height: 600px;
}
option.unavailable {
  color: #EEEEEE;
}
</style>
<script src="{{ STATIC_URL }}/jquery/js/jquery.form.js"></script>
{% endblock %}

{% block form %}
{{ block.super }}
{% addtoblock "endscripts" %}
{% include "_create_course.html" %}
{{ create_course_form.media.js }}
<script>
(function ($) {
  $(function () {
    var getJSON = function(url) {
      var res;
      $.ajax({
            type: 'GET',
            url: url,
            dataType: 'json',
            success: function(data) {
              res = data;
            },
            async: false
      });
      return res;
    };
    $('.courses-selector').on('change', function (){
       $('.courses-selector').not(this).val('');
       $('#id_document_copyrights-course_code').val($(this).val());
       $('#id_document_copyrights-course_name').val($('option:selected', this).text());
    });
    $('#id_document_copyrights-ue').on('change', function () {
      var value = $(this).val();
      if (value) {
        var url = '/entity/' + value + '/';
        var json = getJSON(url);
        var url = '../../course-list/';
        url = url + '?ue=' + json.code + '#ue-course';
        $('#create-course .miller-columns').millercolumns('setItem', value)
        $('#id_entity').trigger('change');
      } else {
        var url = '../../course-list/';
        url = url + '?ue=';
      }

      $.get(url, function (data) {
        var $content = $(data);
        $('#ue-course-container').html($('#ue-course', $content));
        var val = $('#id_document_copyrights-course_code').val();
        $('.courses-selector').val(val);
        $('.courses-selector').on('change', function (){
           $('.courses-selector').not(this).val('');
           $('#id_document_copyrights-course_code').val($(this).val());
           $('#id_document_copyrights-course_name').val($('option:selected', this).text());
        });
      });
    });
    $('#create-course').on('shown', function () {
      $('.miller-columns').millercolumns('refresh');
    });
    function toggle_mycourse_panel() {
      var val = $('#id_document_copyrights-licence').val();
      try {
        val = parseInt(val);
      } catch (err) {
        val = -1;
      }
      if (licence_pks_with_mycourse_tag.indexOf(val) != -1) {
        $('#mycourse-block').show('slow');
        $('.miller-columns').millercolumns('refresh');
      } else {
        $('#mycourse-block').hide('slow');
      }
    }
    function update_course_name() {
      var entity_id = $('#id_entity').val();
      var td_group = $('#id_td_group').val();
      var $name = $('#id_course_label');
      var delegate = $('#create-course .miller-columns').millercolumns('delegate');
      var item = delegate.cache[entity_id];
      var ue = item;
      var $msg = $('#create-course .future-name');
      while (item && item.type != 'version diplome') {
        item = delegate.cache[item.parent_id];
      }
      var diploma = item;
      if (item == undefined) {
        $name.addClass('alert');
        $name.text("La sélection n'est pas une unité d'enseignement.");
      } else {
        var sponsor_name = '{{ object.sponsor_name }}';
        var scholar_year = '{{ course_year }}';
        var diploma_name = diploma.name;
        var group = '';
        var year = '';
        if (td_group) {
          group = '_Gr' + td_group;
        }
        if (scholar_year.indexOf('-') != -1) {
          year = scholar_year.substr(0, scholar_year.indexOf('-'));
        } else {
          year = scholar_year;
        }
        var course_code = ue.code.toUpperCase() + '_' + year + group;
        var course_name = diploma.name.toUpperCase() + '_' + scholar_year + '_' +
          ue.description + group + '_' + sponsor_name;

        $name.removeClass('alert');
        content = "<span><label>Code</label>"+course_code+"</span>";
        content += "<span><label>Nom</label>"+course_name+"</span>";
        $name.html(content);
      }
    }
    $('#id_document_copyrights-licence').on('change', function () {
      toggle_mycourse_panel();
    });
    toggle_mycourse_panel();
    function update_course() {
      var val = $('#id_document_copyrights-course_code').val();
      $('.courses-selector').val(val);
    };
    function install_form() {
      $('#id_entity').on('change', update_course_name);
      $('#id_td_group').on('keyup', update_course_name);
      $('#id_subscription_policy').on('change', function() {
        if ($(this).val() == 'password') {
          $('#div_id_password').parent().show();
        } else {
          $('#div_id_password').parent().hide();
        }
      });
      $('#create-course form').ajaxForm({
        dataType: 'json',
        success: function (content, statusText, xhr, form) {
          if (content.success) {
            alert('Cours ' + content.course_code + ' créé.');
            $('#create-course').modal('hide');
            $('#div_id_document_copyrights-ue .miller-columns').millercolumns(
              'setItem', ''+content.entity_pk);
            $('#id_document_copyrights-course_code').val(content.course_code);
            $('#id_document_copyrights-course_name').val(content.description);
            $('#id_document_copyrights-ue').trigger('change');
          } else {
            var newform = $(content.html);
            $('#create-course form').replaceWith($('form', newform));
            window.install_django_miller_columns();
            install_form();
          }
        }
      });
      update_course_name();
    }
    install_form();
    update_course();
  })
})(window.jQuery)
</script>
{% endaddtoblock %}
{% endblock %}

polynum_blackboard/templates/old.html
<form class="form-horizontal">
<div class="control-group">
<label for="mycourse" class="control-label">Diffusion dans MyCourse</label>
<div class="controls">
  {% with mycourse=1 %}
  <input type="checkbox" id="mycourse" name="mycourse" {% if mycourse %}checked{% endif %}>
</div>
<style>
  #diffusion { margin-left: 2em; border-left: 1px solid #DDD; padding: 1ex; }
  .element-pedagogique { color: green; font-weight: bold; }
  span.error { color: red }
  #course-type-new-block { display: none; }
</style>
{% if not mycourse %}
<style>
  #diffusion { display: none; }
</style>
{% endif %}
{% endwith %}
</div>
<div id="diffusion" class="control-group">
  <div class="control-group">
    <label for="visible" class="control-label">Fichier visible aux étudiants</label>
    <div class="controls">
      <input type="checkbox" id="visible" checked>
    </div>
  </div>
  <div class="control-group">
    <label for="control-type-owner" class="control-label">Dans un de mes cours</label>
    <div class="controls">
      <input type="radio" id="course-type-owner" name="course-type" {% if mycourse %}checked{% endif %}>
      <select id="courses-owner" class="courses">
        <option value="">---</option>
        <option disabled>A</option>
        <option disabled>B (indisponible)</option>
      </select>
    </div>
  </div>
  <div class="control-group">
    <label for="control-type-sponsor" class="control-label">Dans un cours du commanditaire</label>
    <div class="controls">
      <input type="radio" id="course-type-sponsor" name="course-type">
      <select id="courses-sponsor" class="courses">
        <option value="">---</option>
        <option>A</option>
        <option>B</option>
      </select>
    </div>
  </div>
  <div class="control-group">
    <label for="control-type-ue" class="control-label">Dans un cours de l'UE </label>
    <div class="controls">
      <input type="radio" id="course-type-ue" name="course-type">
      <select id="courses-ue" class="courses">
        <option value="">---</option>
      </select>
    </div>
  </div>
  <div class="control-group">
    <label for="control-type-new" class="control-label">Créer un nouveau cours</label>
    <div class="controls">
      <input type="radio" id="course-type-new" name="course-type">
    </div>
    <div class="controls" id="course-type-new-block">
      <div class="control-group">
        <label for="control-type-ue">UE du nouveau cours (les UE sont affichées en vert)</label>
        <input type="hidden" id="ue">
        <div id="ue-selector">
        </div>
        <label for="control-type-ue">Groupe de TD (facultatif)</label>
        <input type="text" id="td-group">
        <div class="control-group">
          <label for="control-type-new" class="control-label">Ouvert aux visiteurs</label>
          <div class="controls">
            <input type="checkbox" name="open-to-visitors">
          </div>
        </div>
        <p>Nom du nouveau cours: <span id="course-name"></span>
      </div>
    </div>
  </div>
</div>
</form>


{% addtoblock "css" %}
<link href="{{STATIC_URL}}eo/css/eo.millercolumns.css" rel="stylesheet">
{% endaddtoblock %}

{% addtoblock "endscripts" %}
<script src="{{STATIC_URL}}jquery/js/jquery-ui.js"></script>
<script src="{{STATIC_URL}}eo/js/eo.millercolumns.js"></script>
<script src="{{STATIC_URL}}eo/js/eo.django.millercolumns.widget.js"></script>
<script>
  $(function () {
  var MyCourseDelegate = PolynumDelegate('ue');
  function UpdateCourseName() {
    var item = $('#ue-selector').millercolumns('getSelection');
    var parents = MyCourseDelegate.getParents(item);
    var diplome;
    var ue = MyCourseDelegate._getItem(item);
    if (ue.type != 'element pedagogique') {
      $('#course-name').html('<span class="error">L\'entité sélectionnée n\'est pas une UE</span>');
      return;
    }
    for (i = parents.length - 1; i >= 0; i--) {
       var data = MyCourseDelegate._getItem(parents[i]);
       if (data.type == 'etape') {
         diplome = data;
         break;
       }
     }
     var course_name = ue.code+'_2012';
     var group = $('#td-group').val();
     if (group) {
       course_name += '_' + group;
     }
     course_name += '_{% firstof user.get_full_name user.username %}';
     $('#course-name').text(course_name);
  }
  MyCourseDelegate.old_selectItem = MyCourseDelegate.selectItem;
  MyCourseDelegate.old_isLeaf = MyCourseDelegate.isLeaf;
  MyCourseDelegate.is
  MyCourseDelegate.selectItem = function (item) {
    $('#course-type-new').attr('checked', 1);
    this.old_selectItem(item);
    UpdateCourseName();
  }
  $('#td-group').keyup(function () {
    UpdateCourseName();
  });
  $('#ue-selector').millercolumns({delegate: MyCourseDelegate});
  if ('{{object.entity.id}}') {
    $('#ue-selector').millercolumns('setItem', '{{object.entity.id}}');
  }
  $('#mycourse').change(function () {
    $('#diffusion').toggle();
    return true;
  });
  $('.courses').each(function (i, v) {
    if ($('option', v).not('[disabled]').length < 2) {
      $('select, input', $(v).parent()).attr('disabled', 1);
      $('<span>Aucun cours disponible</span>').appendTo($(v).parent());
    }
  });
  $('#course-type-new').change(function (){
    $('#course-type-new-block').toggle();
    $('#ue-selector').millercolumns('refresh');
    UpdateCourseName();
  });
})
</script>
{% endaddtoblock %}